### PR TITLE
Improve GeoCode Address Lookup

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/geocode_ui.py:
   Change order of fields for found addresses so that the
   address field will expand to fill the box and will expand
   when the box expands.
   Handle the case where no address is found that matches
   Have entry box expand when the longer addresses are entered.
   Clean up some log noise.

### CODE REVIEW

**Review by ka5mye — APPROVED** [review]
I got the D-Rats Has Encountered an Error popup when I put in a bogus address.  I clicked Ignore and control went back to the look-up window.  Entered a proper address and it was found with no problem.

**Comment by wb8tyw** [comment]
If you got a popup, that is still a bug.   Are you able to get the line number of the crash from where the popup was?

**Comment by ka5mye** [comment]
John:  

I’ll try to that.

Rod
-------------------------------
Rodney Whitaker
***@***.***

**Comment by ka5mye** [comment]
John:

 Here is everything from the D-Rats has encountered an error pop-up.
Debug Log Tab -> Details:

Traceback (most recent call last):

  File "/Users/rww/drats_11_2023/wb8tyw/D-Rats/d_rats/geocode_ui.py", line 253, in prepare_page
    self.prepare_conf(assistant, page)

  File "/Users/rww/drats_11_2023/wb8tyw/D-Rats/d_rats/geocode_ui.py", line 232, in prepare_conf
    self.vals["AddressList"].get_selected(True)

  File "/Users/rww/drats_11_2023/wb8tyw/D-Rats/d_rats/listwidget.py", line 222, in get_selected
    return lst.get(iter_val, *tuple(range(self._ncols)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/rww/opt/anaconda3/envs/radio_m1_5/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 923, in get
    values.append(self.get_value(treeiter, col))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: Argument 1 does not allow None as a value

Thanks,

Rod
-------------------------------
Rodney Whitaker
***@***.***

**Comment by maurizioandreotti** [comment]
tested on macos, it seems ok

**Comment by wb8tyw** [comment]
Forced push as there were no comments in the changed code and needed to pick up the previously landed PR.

This should fix the crashes that have been reported to me.

**Comment by ka5mye** [comment]
I tested this in my local repo …/wb8tyw/D-Rats in
the wb8tyw_gcode branch.  
In Preferences, GPS Config, clicked on Lookup and put in
my QTH address and all worked as it should.

Next, I put in a bogus address and nothing was found, and the popup,
D-Rats has encounter an error, did not come up.  Worked as it should.

This push cleared up the errors I saw earlier.

KA5MYE
-------------------------------
Rodney Whitaker
***@***.***

**Review by ka5mye — APPROVED** [review]

**Comment by ka5mye** [comment]
I should have mentioned the repo version was
bf1a3ff3a8e340b489d63d21218a1ed4085ddf25

KA5MYE
-------------------------------
Rodney Whitaker
***@***.***

**Pull request merged**
