### PR TITLE
Fixes for for 0.4.0 release

### PR DESCRIPTION
**Pull request by wb8tyw**
These mainly affect PIP installed D-Rats.

Fixed various crashes seen on when running the PIP installed tarball, missing directories, or from existing incorrect data in the D-Rats configuration files.

Add the Certificate Authority package for the MSYS2 environment.

README.md:
docs/source/d_rats.rst:
d_rats/ui/main_files.py:
  Minor updates.

share/d-rats.desktop:
share/d-rats_repeater.desktop:
  Fix path to icon to match current conventions.

d-rats_safe_mode.bat:
distXP.bat:
PKG-INFO:
  Removed as obsolete.

d_rats/config.py:
  Add getint_tolerant method for reading data from the
  D-Rats configuration file that may be in the wrong format.

d_rats/config.py:
d_rats/dplatform.py:
  Use makedirs() instead of mkdir() to make sure parent
  directories exist.
  Minor fixes for pylance and docstrings.

d_rats/map/mapdraw.py:
  Use the dplatform.sys_data for looking up the broken_tile.png.
  Minor fixes for pylance and docstrings.

d_rats/ui/main_messages.py:
  Convert dict_keys object to list to prevent crash.
  Minor fixes for pylance and docstrings

d_rats/version.py:
  Fix lookup for setup_version.py for document generation.

python_prebuild.py:
  Make sure changes directory is present.

setup.py:
  Missing the gzipped man pages.
  Locale files put in the wrong directory.
  D-rats2.xpm should be put in share/pixmaps.

msys2_packages.sh:
  Add CA certificate bundle package.

### CODE REVIEW

**Comment by wb8tyw** [comment]
The openstreetmap.com or openstreetmap.de are nor working for me, so I had to test with thunderforest maps.

**Comment by wb8tyw** [comment]
Test pip installable tarball at https://groups.io/g/d-rats/files/D-Rats/D-RATS%20pre-release/D-Rats-0.4.0.dev1.tar.gz

An account for https://groups.io/g/d-rats is needed for downloads.

**Comment by flyingfrawg** [comment]
John,
Finally in a position to dive back into this project (life happens!).
Is there a "succinct" set of setup instructions. 
A linear checklist would be best, teased out per OS if at all possible.
My current observations: Reading comments seems to jump about a bit between original info, Mario's contributions, and yours. My eventual objective will be to test and document some "end user" instructions.
If you can point me in the right direction, I'll try to get caught up and test locally on Win10 and on some RPi linux variant.
If this request is premature, tell me - won't hurt my feelings.
Jack - KD4IZ

**Comment by wb8tyw** [comment]
@flyingfrawg

For development and general use, we have the [WIKI](https://github.com/ham-radio-software/D-Rats/wiki) which could really use some work, and volunteers who are able to update it while learning / re-learning D-Rats would be really helpful.

The README.md file should have what is needed to get started, but I will admit is also could use some updating, along with the  install.txt.  The install.txt should just reference the README.md file section for the install to reduce duplication in the future.

Both are currently deficient in many of the areas you mention, the most work was put into [Windows Install Instructions](https://github.com/ham-radio-software/D-Rats/wiki/010.010-Installation-of-D-Rats-on-Microsoft-Windows).  Linux is typically simpler in this case and usually Linux users know how to a lot of the operations that are not currently in the WIKI and or the README.md file.

General questions about D-Rats are best sent to the [D-Rats mailing list](https://groups.io/g/d-rats) and not as comments to open PRs.  That may get faster and better responses, and again it would be great if good answers that work make it into the [WIKI](https://github.com/ham-radio-software/D-Rats/wiki)

**Comment by flyingfrawg** [comment]
Thanks John.Contacted you you because of documentation. Have experience with Wiki editing. I’ll follow your pointers and see how it goes. Not as concerned about Linux since I don’t use it that much any longer. As you say most linux users can work  through it because they often do compile- sometimes customize and compile.Jack Spitznagel KD4IZSent from my iPhoneOn Apr 16, 2023, at 11:51, John E. Malmberg ***@***.***> wrote:﻿
@flyingfrawg
For development and general use, we have the WIKI which could really use some work, and volunteers who are able to update it while learning / re-learning D-Rats would be really helpful.
The README.md file should have what is needed to get started, but I will admit is also could use some updating, along with the  install.txt.  The install.txt should just reference the README.md file section for the install to reduce duplication in the future.
Both are currently deficient in many of the areas you mention, the most work was put into Windows Install Instructions.  Linux is typically simpler in this case and usually Linux users know how to a lot of the operations that are not currently in the WIKI and or the README.md file.
General questions about D-Rats are best sent to the D-Rats mailing list and not as comments to open PRs.  That may get faster and better responses, and again it would be great if good answers that work make it into the WIKI

**Comment by maurizioandreotti** [comment]
I have done some tests with k3pdr ratflector:

### Connectivity
- connect (k3pdr): works
- request ping from all station connected: works
- show list of connected startion: works
- request position from all station connected: works

### Config
- open config window: works
- save config: works
- change map: works


### MAP
- ctrl-m to show map: works
- map - delete cached tiles: works
- map- reload tiles: works
- show location of a remote station: works

### File transfer
- file transfer dowload: works 
- file transfer upload: works (i opened a couple of bugs on the experience, but i think were aready there)

### Chat
- chat to "main" channel: works
- chat to "filtered tab": works
BUT - getting disconnected after a while, to force reconnect, i did a "ping all" 
(in v.0.3.x it was necessary to edit prefs and save to force a reconnect)

### Email
- not tested

**Review by maurizioandreotti — DISMISSED** [review]

**Comment by wb8tyw** [comment]
Updated with a MAC-OS fix.
Will not have time to make a new tarball until this weekend.

**Comment by maurizioandreotti** [comment]
downloaded patch for Mac, this is  console output:

```
cd D-Rats-wb8tyw_bugfix146 
(d-rats4) maurizio@Air-di-maurizio D-Rats-wb8tyw_bugfix146 % ./d-rats.py 
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/version.py", line 312, in _get_version
    with open(join(module_dir, 'PKG-INFO')) as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/PKG-INFO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/./d-rats.py", line 37, in <module>
    from d_rats.version import __version__
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/version.py", line 325, in <module>
    DRATS_VERSION_NUM = GLOBAL_VERSION.short_version
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/version.py", line 82, in short_version
    self._get_short_version()
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/version.py", line 69, in _get_short_version
    cls._get_version()
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/version.py", line 319, in _get_version
    cls._pep440_version = cls._pep440_version + '.dev0'
                          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
(d-rats4) maurizio@Air-di-maurizio D-Rats-wb8tyw_bugfix146 % ls ../D-Rats-0.4.0.dev1/PKG-INFO 
../D-Rats-0.4.0.dev1/PKG-INFO
```


copyed PKG-INFO from former version and restarted d-rats... it starts!

**Comment by wb8tyw** [comment]
Uploaded [D-Rats-0.4.0.dev4.tar.gz](https://groups.io/g/d-rats/files/D-Rats/D-RATS%20pre-release/D-Rats-0.4.0.dev4.tar.gz)

For the pip installed tarball:
- Fix the bugs in the version lookup.  Version now displays as accurately from tarballs from pull requests.
- Fix the location for the pre-built message catalog files.
Generate the PKG-INFO file, but PIP install does not put it anyplace useful for D-Rats for use.

**Comment by wb8tyw** [comment]
Is this Pull Request (PR) now ready to land?

**Comment by maurizioandreotti** [comment]
I tested and on my cambook air it works

**Review by maurizioandreotti — APPROVED** [review]
ok for me

**Pull request merged**
