### PR TITLE
Install D-Rats in MobaXterm fixes

### PR DESCRIPTION
**Pull request by wb8tyw**
Install script needs to build the translation database.

d-rats_in_mobaxerm_install.sh
  Add packages needed to build the translation database
  and call script to do the build.

d_rats/aprs_icons.py:
  Fix Typographical error.

d_rats/mainwindow.py:
  Fix path for d-rats logo for about dialog

d_rats/version.py:
  Fix git version lookup

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
clicking to get the about window I get the error popup:

Traceback (most recent call last):
```

  File "/drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git/d_rats/mainwindow.py", line 258, in _activate_about
    logo = GdkPixbuf.Pixbuf.new_from_file_at_size("images/d-rats2.png", 64, 64)

gi.repository.GLib.GError: g-file-error-quark: Failed to open file 'images/d-rats2.png': No such file or directory (4)
```

and in console:

```

INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 264, in <module>
    main()
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 258, in main
    app.main()
  File "/drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git/d_rats/mainapp.py", line 2215, in main
    self.run(None)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gio.py", line 44, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 105, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

```

**Comment by wb8tyw** [comment]
Updated the wiki on how to test a pull request using MobaXterm.

https://github.com/ham-radio-software/D-Rats/wiki/010.020-Installation-of-D%E2%80%90Rats-on-Microsoft-Windows-with-MobaXterm#pull-request-testing

**Review by maurizioandreotti — APPROVED** [review]
i was wrong, still getting error in about window.

I think it's looking in the wrong folder

------------
this is the pop.up
```
Traceback (most recent call last):

  File "/drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git/d_rats/mainwindow.py", line 258, in _activate_about
    logo = GdkPixbuf.Pixbuf.new_from_file_at_size("images/d-rats2.png", 64, 64)

gi.repository.GLib.GError: g-file-error-quark: Failed to open file 'images/d-rats2.png': No such file or directory (4)
```

---------------------------


  20/11/2023   01:06.44   /home/mobaxterm  ./d-rats
```
fatal: non è un repository Git (né lo è alcun genitore fino al punto di mount /drives)
Mi fermo al limite del filesystem (l'opzione GIT_DISCOVERY_ACROSS_FILESYSTEM non è impostata).
```

this initial statement says that there is a general error and theerefore it stops at "filesystem limit"

```


/usr/local/lib/pypi/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
INFO:Spelling:Demand-opening aspell...
INFO:Spelling:Tested spelling okay: ['spelling,', 'spelino,', 'peeling,', 'soling,', 'spring,', 'sterling,', 'spline,', 'feeling']
INFO:D-Rats:main: re-config option found -- Reconfigure D-rats
INFO:D-Rats:main: args.config = /home/mobaxterm/.d-rats-ev
INFO:DratsConfig:File /home/mobaxterm/.d-rats-ev/d-rats.config
INFO:MainApp:_refresh_lang: Setting language to: English
INFO:MainApp:set_locale: OS Locale set to: en_US.UTF-8
INFO:MainApp:D-RATS v0.4.1.dev21 starting at Mon Nov 20 01:06:57 2023 on Platform UnixPlatform:
  configuration:       /home/mobaxterm/.d-rats-ev
  system_data: /drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git
  OS version: CYGWIN_NT-10.0-19045-WOW64 Mao-IdeaPad-500 3.3.5-341.i686 2022-06-12 08:16 UTC i686
INFO:MainApp:load position from config file
INFO:MainApp:_static_gps: Configuring the Static position: 45.802020,9.430000
INFO:MainApp:_static_gps: Mapserver not active: False, call: IZ2LXI-2
INFO:StaticGPSSource:StaticGPSPosition: UNKNOWN reporting 45.8020,9.4300@0 ft at 01:06:57
INFO:D-Rats:main: reloading app


INFO:MainApp:_refresh_lang: Setting language to: English
INFO:MainApp:set_locale: OS Locale set to: en_US.UTF-8
INFO:MainApp:load the main window

(d-rats.py:1471): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
INFO:MainApp:load main window with self config
INFO:LocalFileV:refresh: Adding local file `/home/mobaxterm/D-RATS Shared/3_Mode Overview.pdf'
INFO:LocalFileV:refresh: Adding local file `/home/mobaxterm/D-RATS Shared/Hello.txt'

(d-rats.py:1471): Gtk-WARNING **: Attempting to add a widget with type GtkBox to a GtkMenuItem, but as a GtkBin subclass a GtkMenuItem can only contain one widget at a time; it already contains a widget of type GtkAccelLabel
INFO:DRatsPluginServer:Started serve_forever() thread
INFO:MessageRouter:_route_via_station: Starting message router thread
INFO:MainApp:connect main window
INFO:MainApp:connect tabs
INFO:MainApp:going online
INFO:MainApp:create map window object-----
INFO:MapWindow:init MapWindow
INFO:MessageRouter:_run_one: Station list was empty
INFO:MainApp:create map window object: connect object-----
INFO:MainApp:query local gps device to see our current position
INFO:MainApp:invoke config refresh
INFO:MainApp:Refreshing config...
INFO:gps:set_units: Set GPS units to Metric
INFO:MainApp:refresh comms
INFO:MainApp:_refresh_comms: Re-Starting ports_0
INFO:MainApp:Starting Comms
INFO:MainApp:_refresh_comms: Re-Starting ports_1
INFO:MainApp:Starting Comms
INFO:MainApp:_refresh_comms: Re-Starting ports_2
INFO:MainApp:Starting Comms
INFO:MainApp:start_comms: Starting port ports_2 (pldares.ratflector.com)
INFO:MainApp:_refresh_comms: Re-Starting ports_3
INFO:SocketDataPath:connection to pldares.ratflector.com 9000
INFO:MainApp:Starting Comms
INFO:MainApp:_refresh_comms: Re-Starting ports_4
INFO:MainApp:Starting Comms
INFO:MainApp:_refresh_comms: Re-Starting ports_5
INFO:MainApp:Starting Comms
INFO:MainApp:check_comms_status: Ports expected to be already started:
INFO:MainApp:check_comms_status: pldares.ratflector.com
INFO:MainApp:check_comms_status: Checking all Ports from config:
INFO:MainApp:check_comms_status: portid ports_0
INFO:MainApp:check_comms_status: Port alabama.ratflector.com not started
INFO:MainApp:check_comms_status: portid ports_1
INFO:MainApp:check_comms_status: Port k3pdr.dstargateway.org not started
INFO:MainApp:check_comms_status: portid ports_2
INFO:MainApp:check_comms_status: Port pldares.ratflector.com already started!
INFO:MainApp:check_comms_status: portid ports_3
INFO:MainApp:check_comms_status: Port RAT not started
INFO:MainApp:check_comms_status: portid ports_4
INFO:MainApp:check_comms_status: Port sewx.ratflector.com not started
INFO:MainApp:check_comms_status: portid ports_5
INFO:MainApp:check_comms_status: Port sttammany.ratflector.com not started
INFO:MainApp:_refresh_gps : GPS: False on @4800
INFO:MainApp:_static_gps: Configuring the Static position: 45.802020,9.430000
INFO:MainApp:_static_gps: Mapserver not active: False, call: IZ2LXI-2
INFO:StaticGPSSource:StaticGPSPosition: UNKNOWN reporting 45.8020,9.4300@0 m at 01:07:05
INFO:MainApp:_refresh_map: reconfigure Mapwindow with new map
INFO:MainApp:_refresh_map: reconfigured mapurl to: https://tile.thunderforest.com/landscape/
INFO:MainApp:_refresh_map: reconfigured mapkey to: ?apikey=5a1a4a79354244a38707d83969fd88a1
INFO:MainApp:_refresh_lang: Setting language to: English
INFO:MainApp:set_locale: OS Locale set to: en_US.UTF-8
INFO:SocketDataPath:getline: Host does not require authentication
INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 264, in <module>
    main()
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 258, in main
    app.main()
  File "/drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git/d_rats/mainapp.py", line 2215, in main
    self.run(None)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gio.py", line 44, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/home/mobaxterm/d-rats-git/d-rats.py", line 105, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(d-rats.py:1471): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(d-rats.py:1471): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed


```

**Comment by KP4AJ** [comment]
Sorry guys been dealing all weakened with the 8EL OP Des 6M Yagi antenna (getting down, fixing swr and getting it up again.  Next days have several exams to administer at University.  Will catchup after Wednesday.

**Pull request merged**
