### PR TITLE
Invalid DPRS message log flooding

### PR DESCRIPTION
**Pull request by wb8tyw**
The config dialog allowed creating an invalid default GPS comment, and this resulted in the mainapp on a timer continously logging it.

This change supresses the logging and replaces the symbol with the APRS INFO KIOSK symbol, which displays as a question mark.

The configuration dialog has been changed for edit buttons to change the APRS GPS-A symbol or the default GPS comment, so only valid configurations should be able to be created.

Users will have to use the GPS config to fix any invalid data.

changes/230.bugfix:
  Describes fixes for NEWS.rst.

d_rats/aprs_dprs.py:
  Refactored from gps.py.

d_rats/aprs_icons.py:
  Refactored from qst.py.

d_rats/config.py:
  Fix the dialogs for selecting APRS and DPRS codes.

d_rats/dratsexception.py:
d_rats/gps.py:
d_rats/mainapp.py:
d_rats/map/markereditdialog.py:
d_rats/qst.py:
d_rats/sessions/rpc.py:
docs/source/d_rats.rst:
  Refactored DPRS APRS conversions from gps.py.
  Refactored APRS selection dialog from qst.py.

### CODE REVIEW

**Comment by wb8tyw** [comment]
I thought that this would be a quick fix, but it turned out to be far more broken that I originally thought.
Refactoring the APRS code into one module for non GTK use and one for GTK dialogs should make this easier to maintain.

**Comment by maurizioandreotti** [comment]
test on macbook

loading the map I cant see my icon at all, regardless how i configure it.

in the bottom part of the map, if i try to remove a station I get an error:

Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map/mapwindow.py", line 511, in marker_delete_handler
    source.save()

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map_sources.py", line 683, in save
    point.get_aprs_symbol(),
    ^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
           ^^^^^^^^^^^^^^^^^^^^^^^

  [Previous line repeated 989 more times]

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-PR/d_rats/map_sources.py", line 117, in __getattr__
    self._retr_hook(_get, name)

RecursionError: maximum recursion depth exceeded

**Comment by ka5mye** [comment]
I do have some odd things going on.  My map symbols are displayed 
on the map.  I can right click in the map, select New Marker Here, and
can select and place a marker but also get an error traceback, see below. 

But when I delete a Station in my list, the station is deleted and I get:
08/28/2023 07:34:20:INFO:MapWindow:marker_delete_handler: Deleting Stations/AD5RB  M
08/28/2023 07:34:20:INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "d-rats.py", line 250, in <module>
    main()
  File "d-rats.py", line 244, in main
    app.main()
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/mainapp.py", line 2131, in main
    self.run(None)
  File "/Users/rww/opt/anaconda3/envs/radio/lib/python3.8/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "d-rats.py", line 94, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",

Then when adding new Station marker, I got:

08/28/2023 07:35:18:INFO:MapWindow:set_mark_at: Misc,Misc
08/28/2023 07:35:18:INFO:MapWindow:set_mark_at: Adding new point STATION to Misc
Traceback (most recent call last):
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map/mapwindow.py", line 736, in popup_newmarker_handler
    self.set_mark_at()
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map/mapwindow.py", line 997, in set_mark_at
    source.save()
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map_sources.py", line 683, in save
    point.get_aprs_symbol(),
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
  File "/Users/rww/drats_07_2023/wb8tyw_aprs_fix/D-Rats/d_rats/map_sources.py", line 121, in __getattr__
    if not hasattr(self, attrname):
  [Previous line repeated 493 more times]
RecursionError: maximum recursion depth exceeded

Then when I close the map and quit D-Rats, I find that my Stations.csv file in
/Users/rww/.d-rats-ev/static_locations  is now empty.  It had 25 stations in it.
(Fortunately the system backs up the station list in /Users/rww/.d-rats-ev/)

73,
Rod, KA5MYE

-------------------------------
Rodney Whitaker
***@***.***

**Comment by ka5mye** [comment]
All:

 A little more detail.  Restarted D-Rats and then deleted a station,
the “D-Rats has encountered an error” popup window came up.
(I don’t think I had that in my previous email.)   When clicked on 
details, I got the traceback lines that were in Maurizio’s message
displayed in the popup.

Then the screen showed what was in the first part of my message.

I closed D-Rats and indeed my Stations.csv file was empty.

73,
Rod
-------------------------------
Rodney Whitaker
KA5MYE
***@***.***

**Comment by wb8tyw** [comment]
I am not sure if I will be able to do much diagnosis before this Sunday.

It is not obvious what this PR did that could cause this additional misbehavior, as there should have been no functional changes to the map_source point handling.   Some variables were renamed to be more accurate, and a routine was moved to a new module.

There is already a ticket open on the map sources, because it is not properly validating user input or making sure that the map source data file is properly formatted on write.   https://github.com/ham-radio-software/D-Rats/issues/119

**Comment by wb8tyw** [comment]
I have verified that this PR did in fact cause this issue though.  I can not reproduce it on the master branch.
It has been so long since I did anything with the static station file.  It looks like it is not allowing me to add anything to the empty file from the GUI.

**Comment by ka5mye** [comment]
In the Stations panel if I click on Ping all Stations, then I can
choose Request Position for one of the station (online), it does get 
added to my Stations.csv file and will be shown on the map.

73,
Rod
-------------------------------
Rodney Whitaker
***@***.***

**Comment by wb8tyw** [comment]
On the previous push, in my hurry, I forgot to fully fix the Map Marker dialog handling to use the fixed APRS routines.
The current fix should take care of that, and make it much easier to edit anything that needs a APRS or DPRS icon code.

**Comment by wb8tyw** [comment]
A bug has been discovered if you are not using an APRS icon with an overlay, it can cause a d-rats error pop-up.

**Comment by wb8tyw** [comment]
The previous push introduced a modified dialog for creating / editing map markers, config / GPS APRS/DPRS symbols, and for the QST with an DPRS code.

**Comment by ka5mye** [comment]
The commit you sent in the email at 7:30 MDT has fixed
the problems I found yesterday.

Thanks.
-------------------------------
Rodney Whitaker
***@***.***

**Comment by KP4AJ** [comment]
Hi:
Not sure if this fix is already applied to git code.  Having this:
09/19/2023 09:13:52:INFO:GPSPosition:_parse_dprs_comment: Failed to parse DPRS comment: BN  *20
09/19/2023 09:13:52:INFO:GPSPosition:_parse_dprs_comment: CHECKSUM(KP4AJ-L): 69 != 32
09/19/2023 09:13:52:INFO:GPSPosition:_parse_dprs_comment: Checksum : *20
09/19/2023 09:13:52:INFO:GPSPosition:_parse_dprs_comment: _checksum: *45
09/19/2023 09:13:52:INFO:GPSPosition:_parse_dprs_comment: astidx   : 4
09/19/2023 09:13:55:INFO:GPSPosition:_parse_dprs_comment: Failed to parse DPRS comment: BN  *20
09/19/2023 09:13:55:INFO:GPSPosition:_parse_dprs_comment: CHECKSUM(KP4AJ-L): 69 != 32
09/19/2023 09:13:55:INFO:GPSPosition:_parse_dprs_comment: Checksum : *20
09/19/2023 09:13:55:INFO:GPSPosition:_parse_dprs_comment: _checksum: *45
09/19/2023 09:13:55:INFO:GPSPosition:_parse_dprs_comment: astidx   : 4
09/19/2023 09:13:58:INFO:GPSPosition:_parse_dprs_comment: Failed to parse DPRS comment: BN  *20
09/19/2023 09:13:58:INFO:GPSPosition:_parse_dprs_comment: CHECKSUM(KP4AJ-L): 69 != 32
09/19/2023 09:13:58:INFO:GPSPosition:_parse_dprs_comment: Checksum : *20
09/19/2023 09:13:58:INFO:GPSPosition:_parse_dprs_comment: _checksum: *45
09/19/2023 09:13:58:INFO:GPSPosition:_parse_dprs_comment: astidx   : 4

If code already in place, Where I setup to fix this ?

Thanks!

Edfel
KP4AJ

**Pull request merged**
