### PR TITLE
Fix form save functions

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/formgui.py:
  Fixed some missed libxml to lxml changes.
  Fix some pylint issues.
  Convert logger to class variable.

changes/215.bugfix:
  Description of fix.

### CODE REVIEW

**Review by maurizioandreotti — DISMISSED** [review]
did some tests and no issue to report

**Comment by maurizioandreotti** [comment]
after i saved a form, I closed and reopened d-rats and now i get message that the form is not valid:

`File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/formgui.py", line 1051, in __init__
    self.doc = etree.parse(self._filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src/lxml/etree.pyx", line 3541, in lxml.etree.parse

  File "src/lxml/parser.pxi", line 1879, in lxml.etree._parseDocument

  File "src/lxml/parser.pxi", line 1905, in lxml.etree._parseDocumentFromURL

  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocFromFile

  File "src/lxml/parser.pxi", line 1180, in lxml.etree._BaseParser._parseDocFromFile

  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError

  File "/Users/maurizio/.d-rats-ev/messages/Inbox/form_07062023_192231.xml", line 1

lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/main_messages.py", line 372, in _importmsg
    self.refresh_if_folder(_("Inbox"))

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/main_messages.py", line 533, in refresh_if_folder
    self._messages.refresh()

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/message_list.py", line 416, in refresh
    self._update_message_info(msg_iter)

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/message_list.py", line 365, in _update_message_info
    form = formgui.FormFile(fname)
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/formgui.py", line 1053, in __init__
    raise FormguiFileNotValid("Form file %s is not valid! (%s)" %

d_rats.formgui.FormguiFileNotValid: Form file /Users/maurizio/.d-rats-ev/messages/Inbox/form_07062023_192231.xml is not valid! (Start tag expected, '<' not found, line 1, column 1 (form_07062023_192231.xml, line 1))
`

**Comment by wb8tyw** [comment]
Somehow the file got corrupted.
I can not reproduce this corruption with anti-x linux or windows 7.

Can you save off the file and look at it in a plain text editor and see if anything shows up?

**Comment by maurizioandreotti** [comment]
Retested and working, for what i can see. 
...but i cannot do a review anymore to approve merge...

**Review by maurizioandreotti — APPROVED** [review]

**Review by ka5mye — APPROVED** [review]

**Pull request merged**
