### PR TITLE
Fix filename selection Dialog

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/config.py:
  Use refactored d_rats/filenamebox.py.
  Designate when not a save file operation.

d_rats/filenamebox.py:
  Refactored from d_rats/miscwidgets.py.
  Fix GTK compatibility issues.
  Add save parameter to select proper action button.
  Add Unit test.

d_rats/miscwidgets.py:
  Remove FilenameBox class.

d_rats/qst.py:
  Use refactored d_rats/filenamebox.py.
  Fix GTK compatibility issues.

docs/source/d_rats.rst:
  Add d_rats/filenamebox.py

### CODE REVIEW

**Comment by ka5mye** [comment]
Both computers here are Mac.

Installed wb8tyw_filenamebox.  Went to files and connected to another D-Rats
on another computer.  Initiated a file download from other computer.  It did
finish but the threw an exception and traceback, as shown below starting at Transfer Complete.

06/11/2023 14:28:26:INFO:MainApp:Session Started In: [SESSION 5]: Transfer Completed
06/11/2023 14:28:26:INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "d-rats.py", line 240, in <module>
    main()
  File "d-rats.py", line 234, in main
    app.main()
  File "/Users/rww/drats_06_2023/wb8tyw_filenamebox/D-Rats-wb8tyw_filenamebox/d_rats/mainapp.py", line 2124, in main
    self.run(None)
  File "/Users/rww/opt/anaconda3/envs/radio/lib/python3.8/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/Users/rww/drats_06_2023/wb8tyw_filenamebox/D-Rats-wb8tyw_filenamebox/d_rats/mainapp.py", line 1885, in __file_received
    self.mainwindow.tabs["files"].refresh_local()
  File "/Users/rww/drats_06_2023/wb8tyw_filenamebox/D-Rats-wb8tyw_filenamebox/d_rats/ui/main_files.py", line 367, in refresh_local
    self._notice()
  File "/Users/rww/drats_06_2023/wb8tyw_filenamebox/D-Rats-wb8tyw_filenamebox/d_rats/ui/main_common.py", line 267, in _notice
    self.emit("notice")
  File "d-rats.py", line 93, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",
06/11/2023 14:28:30:INFO:ControlSession:ctl_end: Session 5 ended but not registered
Traceback (most recent call last):
  File "/Users/rww/drats_06_2023/wb8tyw_filenamebox/D-Rats-wb8tyw_filenamebox/d_rats/sessions/control.py", line 123, in ctl_end
    session = self._sm.sessions[ident]
KeyError: 5
06/11/2023 14:28:30:INFO:SessionManager:incoming: Received block 0:1 for session `control’

The transferred file was good.

73,
Rod


-------------------------------
Rodney Whitaker
***@***.***

**Comment by wb8tyw** [comment]
@ka5mye There should be nothing in this change that should cause what you are seeing.  This looks like a new bug.

**Comment by wb8tyw** [comment]
Essentially the only thing that should be user visible in this change is configuration and QST file selections.

**Review by maurizioandreotti — APPROVED** [review]
tested on macos and windows

**Comment by wb8tyw** [comment]
Found some more work to be done on this PR.
There is a partial implementation that is supposed to limit the file selection logic to the desired file types.
I am going to try to complete that.

**Comment by wb8tyw** [comment]
Filename filtering working for Windows, not for my Linux system so leaving that code commented out for non-Windows until we can find out why it is broken inside D-rats.

My suspicion is that something was missed in the GTK-2 to GTK-3 conversion that is causing the failure.

**Comment by wb8tyw** [comment]
Note this PR updates some strings used for language translations, so non-english dictionaries will need to be updated in a future pull request.

**Comment by maurizioandreotti** [comment]
hi @wb8tyw, from the log i dont undertand if this is to be reviewd now or still pending  for linux fixes

**Comment by wb8tyw** [comment]
As an additional change was pushed after it was reviewed, it needs a new review.

Before the next version is tagged, the Italian po files need to be regenerated, reviewed and updated as this PR now adds a few more phrases to them.

**Comment by wb8tyw** [comment]
This PR is ready to be reviewed.  The fixing of the Linux code will have to be a future PR, It looks like it is going to take some investigation to find out why it is not working.

**Comment by wb8tyw** [comment]
Still looking for reviews/approvals.
Have a number of additional PRs waiting to be submitted, and want to avoid having multiple PRs in flight at the same time.

**Pull request merged**
