### PR TITLE
Fix sounds on Linux and Mac OS

### PR DESCRIPTION
**Pull request by wb8tyw**
README.md:
pyproject.toml:
requirements.txt:
  Upated modules needed for sound on non-Windows systems

changes/181.bugfix:
  Describe this fix for future release

d_rats/dplatform*.py:
docs/source/d_rats.rst:
  Move each platform into its own module.
  Add generic sound support.

### CODE REVIEW

**Comment by wb8tyw** [comment]
This should enable sounds on any non-windows platform as long as the pyaudio and pydub modules are installed.

Microsoft Windows was already working and the python3-pydub module is not available for for mysys2.

**Comment by ka5mye** [comment]
This version came up fine.  But for me, doing the Preferences -> Sounds -> Test
generates the error:  ossaudiodev or related package not installed

Have to explore that.

KA5MYE


-------------------------------
Rodney Whitaker
***@***.***

**Comment by ka5mye** [comment]
My error.  I thought I had pyaudio installed but it was not.

Installed and will retest.

KA5MYE


-------------------------------
Rodney Whitaker
***@***.***

**Comment by wb8tyw** [comment]
The "ossdevice" error is removed by this PR, so it should not be coming up while you are testing it.  It was replaced with an error that states the new package names.
This new sound method need pydub and pyaudio to function.
I was only able to test it on Anti-X linux (Debian based) and Windows with Msys2.

**Comment by ka5mye** [comment]
Still get the error.  In my environment:
pyaudio       0.2.11 
pydub         0.25.1

And the INFO from the screen:

06/03/2023 20:01:21:INFO:MacOSXPlatform:play_sound: ossaudiodev or related package not installed

KA5MYE

-------------------------------
Rodney Whitaker
***@***.***

**Comment by dranch** [comment]
OSS is Linux's ancient sound system and should be outright removed.  I'm not familiar with those Python plugins but instead, when you need to play a sound, can just run shell/batch file to do it.  Within that shell/batch file, you can do anything you want and it's simple to maintain.

**Comment by wb8tyw** [comment]
This PR does not use ossaudio, it removes all references to it from D-Rats.
You can see that by looking at the file changed tab, and making sure that all the diffs are expanded.

The log message you are getting is indicating that you are not testing the code in this PR.   If you have this PR code loaded, that loh message can not show up.

**Comment by ka5mye** [comment]
Working on my MacBook Pro.
Something was not right when I did the git clone from the website.
I downloaded the zip file and unzipped. Started D-Rats and the sound
fixes work.  Tested in Preferences and in Chat window.
Approve this fix.
-------------------------------
Rodney Whitaker
***@***.***

**Comment by wb8tyw** [comment]
On the File Changes tab, there is a "review changes" tab.
If you click on that, it opens a box with several options, one of them is to mark your approval of the change.  This is needed to unblock non-admin merging.

**Review by ka5mye — APPROVED** [review]

**Pull request merged**
