### PR TITLE
Finalize 0.4.2 release

### PR DESCRIPTION
**Pull request by wb8tyw**

### CODE REVIEW

**Comment by flyingfrawg** [comment]
Attempted clean install on Win 11 laptop. After several false starts got it to run. No active stations on any of the ratflectors I configured, but queries worked on the ones listed in the ping list. Was able to connect for file transfer to KG5CEN, did not try to retrieve a file. Was able to bring up a log. Map only showed my station. Had several crashes that killed the app. Had trouble copying the errors in the MobiXterm window. Will try again in the AM to see if I can cause a crash and capture the error messages..

**Review by maurizioandreotti — APPROVED** [review]
tested as working on:
- MacOs M1 Sonoma 14.1.1 (in python virtualenv setup via brew)
- Windows 10 - MobaXterm setup
- Windows 10 - MSYS2 MINGW64

**Comment by wb8tyw** [comment]
@flyingfrawg : The crashes of the map are a known issue.
There is no throttling of the map tile download and they are all done in parallel.
If you change zoom level or the center position a lot and there are not already cached tiles, it just adds to the number of tiles being downloaded and eventually it can overload something and it breaks.   Once most of the tiles are cached, it stops crashing.   Seen on may platforms on new installations.

**Comment by VA3MCT** [comment]
I installed today using the  MobaXterm, but need to install on a different
PC to use with an ICOM ID-880H radio, but all seemed to work well.

A few issues with the install info, but I since found some extra info on
using the RAW .sh script and all is good.

73,
Mike Crabtree - VA3MCT

**Pull request merged**
