### PR TITLE
NMEA conversions and MAP fixes

### PR DESCRIPTION
**Pull request by wb8tyw**
Fix NMEA to decimal degree conversions.
Add correction for latitude display on Map.

d_rats/gps.py:
  Move logger to be a class variable.
  Fix nmea2deg routine.

d_rats/map/mapwidget.py:
  Move logger to be a class variable.
  Only recalculate map scale on zoom change.

d_rats/map/maptile.py:
  Move logger to be a class variable.
  Add fudge factor to correct latitude placement.

d_rats/map/mapwindow.py:
  Move logger to be a class variable.
  Adjust event button to be debug logging item.

d_rats/map/mapzoomcontrols.py:
  Need to have mapwidget update scale text on zoom change.

changes/211.bugfix:
  Describe NMEA and decimal Degree fixes.

### CODE REVIEW

**Review by flyingfrawg — APPROVED** [review]
John - Fixes #219 appear to work properly here. Had to use the GPS in my IC-705 as the puck I have is behaving oddly, but location was correct. Map is showing positions without jumping as view is zoomed out. Thanks! - KD4IZ

**Comment by maurizioandreotti** [comment]
I selected a point on the d-Rats map asking its coordinates at zoom level 18 and it does not correspond with the coordinates i see on openstreetmap (same point), see here the coordinates identified by the systems:

image

If I then ask D-rats to center the map on the coordinates of the selected point, it centers on a point slighly south, so  I think that it correcltly goes to the point requested, but than if shows wrong coordinates for the point at the center of the map

**Comment by flyingfrawg** [comment]
Maurizio,That could be caused if some function is truncating the GPS coordinates. I see that problem frequently here, often with both Google and OpenStreetMaps. It occurs in other programs as well. For me me, Gaia GPS and Garmin are consistent and relatively more accurate.Jack - KD4IZSent from my iPhoneOn Jun 25, 2023, at 18:49, MAURIZIO ANDREOTTI ***@***.***> wrote:﻿
I selected a point on the d-Rats map asking its coordinates at zoom level 18 and it does not correspond with the coordinates i see on openstreetmap (same point), see here the coordinates identified by the systems:

If I then ask D-rats to center the map on the coordinates of the selected point, it centers on a point slighly south, so  I think that it correcltly goes to the point requested, but than if shows wrong coordinates for the point at the center of the map

**Comment by wb8tyw** [comment]
It is an issue with mapping the GTK pixels too and from the "slippy" tile coordinates.

It seems that the offset from screen origin on the latitude access is changing slightly with each zoom level.

I can not seem to find a perfect algorithm to match what is going on, and I have spent weeks in the past working on it.

Right now, this is the closest that I have been able to get it to be consistent at all zoom levels for my location.
It is possible that we may need plot out different "fudge factors" for major change in latitude.

If you right click on the D-Rats map it will show what it calculates the GPS coordinates to be at that location.

**Comment by maurizioandreotti** [comment]
What confuse me is that when i tell d-rats to "center here" it takes the coordinates of point where I click (which are wrong for that point, as the point is generally more north vs the coordinates shown) 

but then it seems to move correctly the map to the selected coordinates (so it goes south with respect to the desired point) and then the new center is shown with other wrong coordinates 

In other words it seems that recentering works correcly when it does the got-to-coord but then introduce an error on rendering the coords on the map

**Comment by wb8tyw** [comment]
Can you see if you can find how far off the plotting is for various points at various resolutions to see if we can find some type of pattern?

The "Button # at #, #" log message should show up to show the display coordinates when you right click on a position.   So we want to know the difference between the what the D-Rats maps show for the mouse positions for the right and wrong locations.

Somewhere we are just getting the wrong offset for the latitude in the map calculations, hopefully we can figure out what it is.

**Comment by maurizioandreotti** [comment]
Using PR 209 on Windows/

QTH location coordinates determined by openstreetmap: [45.80043, 9.42844](https://www.openstreetmap.org/#map=19/45.80043/9.42844)

##  Level 18

- my QTH icon (Drats configured at: 45.80043, 9.42844) is show at a point which on openstreemap it has be 45.80119,9.42846 
- While my real QTH is shown by D-Rats with these coords: 45.7996, 9.4284

Se delta are:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mauri/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mauri/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Real coordinates   from Openstreetmap | 45,800430 | 94,284400
-- | -- | --
same point coords on D-Rats | 45,801190 | 94,284600
delta | -0,000760 | -0,000200



</body>

</html>


image

## Level 17
at level 17, the display is similar, and shown coordinates are the same:
image

##Level 16 ..15..14
the situation is the same as lv 18

## Levels < 14
The difference is not perceivable because of the magnification level

**Comment by wb8tyw** [comment]
The algorithm needing adjustment is the code that translates mouse coordinates to or from latitude/longitude.
The information that would be helpful is:
`06/26/2023 07:51:17:INFO:MapWindow:Clicked 3: {'lat': 35.89224867300143, 'lon': -106.29289627075195, 'x': 1150.0, 'y': 1221.0}`
For both the position on the D-Rats map where the point should be and where it shows up.
And maybe we can find some type of pattern for a fix.
The 'x' and 'y' are the mouse coordinates.

**Comment by maurizioandreotti** [comment]
image

Some clicks on the QHT icon:
```

06/27/2023 02:41:09:INFO:MapWindow:Clicked 3: {'lat': 45.80042470930444, 'lon': 9.428442120552063, 'x': 1173.0, 'y': 1189.0}
06/27/2023 02:41:19:INFO:MapWindow:Button 3 at 1175,1194
06/27/2023 02:41:19:INFO:MapWindow:Clicked 3: {'lat': 45.8004060100186, 'lon': 9.428452849388123, 'x': 1175.0, 'y': 1194.0}
06/27/2023 02:41:31:INFO:MapWindow:Button 1 at 1171,1188
06/27/2023 02:41:36:INFO:MapWindow:Button 1 at 1171,1186
06/27/2023 02:41:44:INFO:MapWindow:Button 3 at 1171,1186
06/27/2023 02:41:44:INFO:MapWindow:Clicked 3: {'lat': 45.80043592887293, 'lon': 9.428431391716003, 'x': 1171.0, 'y': 1186.0}
06/27/2023 02:41:49:INFO:MapWindow:Button 3 at 1171,1186
06/27/2023 02:41:49:INFO:MapWindow:Clicked 3: {'lat': 45.80043592887293, 'lon': 9.428431391716003, 'x': 1171.0, 'y': 1186.0}
06/27/2023 02:41:56:INFO:MapWindow:Button 3 at 1170,1187
06/27/2023 02:41:56:INFO:MapWindow:Clicked 3: {'lat': 45.800432189017016, 'lon': 9.428426027297974, 'x': 1170.0, 'y': 1187.0}
06/27/2023 02:42:39:INFO:MapWindow:Button 1 at 1170,1190
06/27/2023 02:42:40:INFO:MapWindow:Button 3 at 1170,1190
06/27/2023 02:42:40:INFO:MapWindow:Clicked 3: {'lat': 45.80042096944777, 'lon': 9.428426027297974, 'x': 1170.0, 'y': 1190.0}
06/27/2023 02:43:20:INFO:MapWindow:Button 3 at 1171,1193
06/27/2023 02:43:20:INFO:MapWindow:Clicked 3: {'lat': 45.800409749876266, 'lon': 9.428431391716003, 'x': 1171.0, 'y': 1193.0}

```

**Comment by ka5mye** [comment]
I zoomed in to my location (Zoom 18) where I can clearly see where my property is.
I right clicked on my house location and got the three lines:

06/26/2023 20:23:30:INFO:MapTile:x_tile 4.789062, y_tile 4.761719
06/26/2023 20:23:30:INFO:MapWindow:Clicked 3: {'lat': 35.89154029995165, 'lon': -106.29301428794861, 'x': 1226.0, 'y': 1011.0}
06/26/2023 20:23:30:INFO:MapTile:x_tile 4.789062, y_tile 4.761719

I then selected Center on this point, and the view changed but my location was north of the
center of the display.  I then went to the center of the display (by eye) and right clicked and got:

06/26/2023 20:24:37:INFO:MapTile:x_tile 4.554688, y_tile 5.257812
06/26/2023 20:24:37:INFO:MapWindow:Clicked 3: {'lat': 35.89098837299867, 'lon': -106.2933361530304, 'x': 1166.0, 'y': 1138.0}
06/26/2023 20:24:42:INFO:MapTile:x_tile 5.757812, y_tile 5.226562

KA5MYE

-------------------------------
Rodney Whitaker
***@***.***

**Comment by maurizioandreotti** [comment]
I just recalled some info,  which could be related or not to what we are seeing here

when in the past I was working on improving the maps for 0.3.x,, D-Rats already had an error displaying an positions placement 

the error was mainly on the vertical placement and was different for each zoom level And also proportional to the latitude: i.e. the "fudge" factor which was correcting the placement for points close at the poles wasnt working for points at the equator.

maybe the fudge shall be calculated on the base of the latitude ?

**Comment by maurizioandreotti** [comment]
QTH still configured to be at:

45,800430 | 94,284400
-- | --



</body>
</html>
I just noted that I get wrong placement on PR 209 wb8tyw_gps:

06/27/2023 11:31:50:INFO:MapTile:x_tile 4.660156, y_tile 4.652344

image

While I get correct placement with PR 220 branch 'wb8tyw_config_noise'
06/27/2023 11:35:47:INFO:MapWindow:Button 1 at 1171,1189

image

**Comment by wb8tyw** [comment]
Yes, I am concerned that the fudge factor is both latitude and zoom specific.

Only this PR has the fudge factor in it, and it appears that the fudge factor only works for my latitude.  So this PR is going to need an update.

We need to find either an improved algorithm or for pixels to/form latitude or a better way to obtain a fudge factor.

**Comment by wb8tyw** [comment]
It turns out that my QTH which was geo-located by the Nominatim shows up on the same wrong location on the OpenStreetMap maps.

So the maps have been rendering correctly with out the fudge factors.

@maurizioandreotti and @ka5mye and @flyingfrawg thanks for the help with this.

Hopefully this will now be ready for merging.

**Comment by ka5mye** [comment]
Sounds good.  Thanks.

-------------------------------
Rodney Whitaker
***@***.***

**Comment by maurizioandreotti** [comment]
at launch of d-rats i now get:

```
Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/mainapp.py", line 1164, in _refresh_location
    self.stations_overlay.add_point(self.__map_point)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'add_point'

```

if ignoring the error i then get:
`Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/mainapp.py", line 502, in do_activate
    self.map = Map.Window(self, self.config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/map/mapwindow.py", line 144, in __init__
    bottom_panel = Map.BottomPanel(self)
                   ^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/map/mapbottompanel.py", line 94, in __init__
    self.controls = MapControls(map_window)
                    ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/map/mapbottompanel.py", line 69, in __init__
    self.zoom_control = Map.ZoomControls(map_window.map_widget)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/map/mapzoomcontrols.py", line 62, in __init__
    Map.Tile.set_zoom(self.__level)

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/map/maptile.py", line 293, in set_zoom
    cls.center.x_tile, cls.center.y_tile)
    ^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'x_tile'`

then, still ingoring error, if I open the map window i get:


`Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/mainapp.py", line 1490, in __show_map_station
    self.map.show()
    ^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'show'`

**Review by maurizioandreotti — COMMENTED** [review]
just launching D-Rats (mac) i get this error:


`File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/formgui.py", line 1051, in __init__
    self.doc = etree.parse(self._filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src/lxml/etree.pyx", line 3541, in lxml.etree.parse

  File "src/lxml/parser.pxi", line 1879, in lxml.etree._parseDocument

  File "src/lxml/parser.pxi", line 1905, in lxml.etree._parseDocumentFromURL

  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocFromFile

  File "src/lxml/parser.pxi", line 1180, in lxml.etree._BaseParser._parseDocFromFile

  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError

  File "/Users/maurizio/.d-rats-ev/messages/Inbox/form_07062023_192231.xml", line 1

lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/main_messages.py", line 372, in _importmsg
    self.refresh_if_folder(_("Inbox"))

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/main_messages.py", line 533, in refresh_if_folder
    self._messages.refresh()

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/message_list.py", line 416, in refresh
    self._update_message_info(msg_iter)

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/ui/message_list.py", line 365, in _update_message_info
    form = formgui.FormFile(fname)
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/formgui.py", line 1053, in __init__
    raise FormguiFileNotValid("Form file %s is not valid! (%s)" %

d_rats.formgui.FormguiFileNotValid: Form file /Users/maurizio/.d-rats-ev/messages/Inbox/form_07062023_192231.xml is not valid! (Start tag expected, '<' not found, line 1, column 1 (form_07062023_192231.xml, line 1))
`

**Review by maurizioandreotti — APPROVED** [review]
tested  maps loading on both windows and macbook air as working.

btw, I noted that on windows it was much faster while on mac tended to be much more slow and with much more errors in console. It come out that on windows I had put http in map urls, while on mac I had https.

anyhow, if equally configured, both systems have similar behaviour

**Pull request merged**
