### PR TITLE
Fix message attachment, e-mail accounts

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/config.py:
  Docstring Fix

d_rats/formgui.py:
  General code cleanup.
  Fix remove_attachment() to work.
  Disable remove and save buttons unless an item is selected.

d_rats/keyedlistwidget.py:
  Fix the set_password cell data function to not use transient data.
  Remove some log noise.

d_rats/ui/message_list.py:
  Remove some log noise.

d_rats/utils.py:
  Remove some obsolete routines.

changes/224.bugfix:
  Doucument fix attempt for account adding.

changes/226.bugfix:
  Document this fix for the NEWS.rst

### CODE REVIEW

**Comment by ka5mye** [comment]
Using an Intel MBP.

Working from the branch wb8tyw_formgui.  Wrote an email with 
an attachment and put it in the outbox in D-Rats.  That generated
a long error string:

07/16/2023 17:09:10:INFO:MessageRouter:_route_msg: Routing message for ***@***.*** to ***@***.***
07/16/2023 17:09:10:INFO:MessageRouter:_route_via_station: src <class 'str'> KA5MYE dst <class 'str'> ***@***.*** msgfn <class 'str'> /Users/rww/.d-rats-ev/messages/Outbox/form_07162023_165529.xml
07/16/2023 17:09:10:INFO:MessageRouter:_run_one: broad-except
Traceback (most recent call last):
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 750, in _run_one
    routed = self._route_message(msg, slist, routes)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 715, in _route_message
    routed = self._route_via_wl2k(src, route, msg)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 670, in _route_via_wl2k
    msg = self._form_to_wl2k_em(addr, msgfn)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 568, in _form_to_wl2k_em
    data = form.get_attachment(name)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/formgui.py", line 1378, in get_attachment
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check
07/16/2023 17:09:10:INFO:Utils.log_exception:-- Exception: --
Traceback (most recent call last):
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 750, in _run_one
    routed = self._route_message(msg, slist, routes)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 715, in _route_message
    routed = self._route_via_wl2k(src, route, msg)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 670, in _route_via_wl2k
    msg = self._form_to_wl2k_em(addr, msgfn)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 568, in _form_to_wl2k_em
    data = form.get_attachment(name)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/formgui.py", line 1378, in get_attachment
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check
Traceback (most recent call last):
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 750, in _run_one
    routed = self._route_message(msg, slist, routes)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 715, in _route_message
    routed = self._route_via_wl2k(src, route, msg)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 670, in _route_via_wl2k
    msg = self._form_to_wl2k_em(addr, msgfn)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/msgrouting.py", line 568, in _form_to_wl2k_em
    data = form.get_attachment(name)
  File "/Users/rww/drats_07_2023/D-Rats/d_rats/formgui.py", line 1378, in get_attachment
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check
07/16/2023 17:09:10:INFO:Utils.log_exception:----------------

Then an email without attachments was sent with no problems.

KA5MYE
-------------------------------
Rodney Whitaker
***@***.***

**Comment by wb8tyw** [comment]
Ok, that is a new problem.  Will try to find a fix for that and update the PR.

**Comment by wb8tyw** [comment]
I have been looking more at the attachment missing issue, and there is a lot of work that is going to be needed to properly fix it, including fully documenting things.   Just tracing through the add attachment code I have found several non-optimal code paths that really need to be cleaned up.

So I would like to get this PR approved for merging and then I will work on finding out why attachments are getting lost, apparently before transmission.

**Comment by wb8tyw** [comment]
Found that the old method of getting the attachment was getting the XML element with the attachment instead of just the attachment data, and this was why the zlib decompression was failing.

This should be ready for testing.

**Comment by wb8tyw** [comment]
Still waiting for a review / test

**Comment by ka5mye** [comment]
John:

 I think I tested this and found an attachment in a regular email failed.
A callsign to callsign email with attachment worked.

Let me know if I need to test again, please.

Thanks,

Rod



-------------------------------
Rodney Whitaker
***@***.***

**Comment by flyingfrawg** [comment]
John,

 

Sorry, I missed the original.

 

I have updated the local install and tested message sending. It worked without error.

 

Jack Spitznagel – KD4IZ

**Comment by wb8tyw** [comment]
Rod, please retest.  Since your first published test results, I fixed the attachment code.  Even though I thought I had tested attachments, the previously checked in code had not been converted to the lxml module.

**Comment by wb8tyw** [comment]
Rod,
by attachment to regular e-mail, is that an e-mail that d-rats received, or an e-mail that d-rats sent.
I have not set up the mail tests since the previous laptop died.

**Comment by ka5mye** [comment]
John:

 The failed attempt was one where I tried to send an email to
***@***.*** ***@***.***> from D-Rats with an attachment.  In the D-Rats destination
I, of course, put ***@***.*** ***@***.***> and I have a WinLink account.

Will try again.

Thanks,

Rod
-------------------------------
Rodney Whitaker
***@***.***

**Comment by ka5mye** [comment]
John:

 This time I had success sending, from D-Rats, an email to ***@***.*** ***@***.***>
with an attachment.  It came in to my inbox with attachment.
In chat tab, the version shown was:  D-RATS v0.4.0.dev19-g779fc01

I approve this pr.

Rod
-------------------------------
Rodney Whitaker
***@***.***

**Review by ka5mye — APPROVED** [review]

**Pull request merged**
