### PR TITLE
Fix lookup of GPS coordinates from address

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/config.py:
  Fix implementation for looking up GPS coords from an Address.
  Demote some log messages to debug level.

d_rats/geocode_ui.py:
  Move some code from config.py for config.py to use this.

changes/199.bugfix
  List this as fixed issue.

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
On Windows 10 :
```
$ gh pr checkout 208
From https://github.com/ham-radio-software/D-Rats
 * branch            refs/pull/208/head -> FETCH_HEAD
```
version being: **0.4.1.dev9-gc6ed30b**, the GPS config window is missing to show the command to lookup  coordinates from a"

image

**Review by ka5mye — COMMENTED** [review]
I did the following: gh pr checkout 208
and got from git branch:
  master
* wb8tyw_geoip
Ran d-rats.py, went to Preferences -> GPS config, clicked on Lookup Tab and entered an address and hit Next

It failed throwing up the: D-Rats has Encountered an Error popup and the screen output in the attached file.
The Chat window showed version D-RATS v0.4.1.dev9-gc6ed30b

[pr208_error.txt](https://github.com/ham-radio-software/D-Rats/files/11818866/pr208_error.txt)

**Comment by ka5mye** [comment]
I did get the Lookup Tab on GPS config.  Screen shot below:



That was on my Intel MBP.  On my M1 MBP, following the same procedure, I did not get
the Lookup Tab.

-------------------------------
Rodney Whitaker
***@***.***

**Review by ka5mye — COMMENTED** [review]
Here is screenshot:

Screen Shot 2023-06-21 at 8 49 20 AM

**Comment by ka5mye** [comment]
On my M1 MBP I did not have geopy installed.  I used conda install geopy
and that installed two packages:
geopy and geographiclib 

Then brought up D-Rats, Pref -> GPS config and the Lookup Tab  was there, entered
an address, hit Next and Locations Found showed the address, hit next and 
Confirm Address showed everything.  Hit Apply and it populated the Latitude
and Longitude windows inGPS config. 

This worked successfully.

Now willl go back to Intel MBP to see if I have everything.

KA5MYE
-------------------------------
Rodney Whitaker
***@***.***

**Comment by ka5mye** [comment]
UPDATE PR 208:  I may have had an environment issue when I tested on the Intel Mac.  Restarted everything and now the Look up GPS coordinates worked.  Gave it an address and all steps worked.  
I have confirmed this works on Intel Mac and M1 Mac.

**Review by ka5mye — APPROVED** [review]

**Comment by wb8tyw** [comment]
`geopy.exc.GeocoderServiceError: [SSL: CERTIFICATE_VERIFY_FAILED]`

This is caused by either the standard certificate bundle missing from the platform or the standard certificate bundle is out of date.

The msys2 mingw64 is not using the Microsoft certificate bundle, and originally I did not have one in the https://github.com/ham-radio-software/D-Rats/blob/master/msys2_packages.sh file.

That file has been updated to include the certificate bundle, so running the current copy should fix the issue as it will update the msys2 environment.  It may also cause the shell session to be restarted, so it may need to be run more than once.

**Comment by maurizioandreotti** [comment]
I can confirm this is working also on Windows 10/Msys  


after updating Windows 10/msys  launching several times the script:

`msys2_packages.sh `

which is present in the D-Rats home folder.

**Review by maurizioandreotti — APPROVED** [review]
tested on Windows 10 and MacOS

**Pull request merged**
